server:
  url: "ws://127.0.0.1:8000"
  timeout: 600

docker:
  image: "wsm/robomme-cpu-runtime:ubuntu22"
  cpus: "0-239"
  env:
    - "ROBOMME_USE_LAVAPIPE=1"
    - "LP_NUM_THREADS=4"
    - "OMP_NUM_THREADS=1"

output_dir: "./results"

benchmarks:
  - benchmark: "robomme_integration.eval.benchmark:RoboMMEOfficialHistoryBenchmark"
    subname: reference-videoplaceorder
    episodes_per_task: 50
    params:
      tasks: [VideoPlaceOrder]
      action_space: joint_angle
      max_steps: 1300
      dataset: test
      send_wrist_image: true
      send_state: true
      send_video_history: true
