"""RoboTTT GR00T action-head wiring: the window-major pairing, the derived widths, the guards.

The port's other tests cover the fast-weight MATH (`test_groot_robottt_fast_weights.py`) and the
window ENUMERATION (`test_groot_seq_windows.py`). This file covers the seam between them: how a
`[B, L, ...]` sequence batch is flattened to `B*L`, how the `[L, B, C]` conditioning is put in the
SAME order, and — since 2026-08-08 — where the fast weights' input widths come from.

TWO FAILURE MODES, BOTH SILENT-BY-DEFAULT, BOTH PINNED HERE.

1. THE PAIRING. The right and wrong flatten orders have identical shapes, both train, and both
   produce a falling loss; the wrong one just pairs every observation with another timestep's
   fast-weight state. So the tests carry per-(window, step) TAGS through both paths and assert
   element-wise identity, plus that the transposed arrangement does NOT match.

2. THE WIDTHS. The first TTT canary died at step 0 on `mat1 and mat2 shapes cannot be multiplied
   (2x132 and 64x256)`: `state_in` had been built at `RoboTTTConfig`'s pi-lineage default
   `state_dim=64` while the real GR00T processor pads proprio to `max_state_dim=132`. The eight
   tests in this file all passed, because every one of them synthesised its tensors AT the config
   dims — the test and the code agreed with each other and neither had ever met the data. The fix
   is structural, not a corrected constant: `DIMS` below is produced by the PRODUCTION function
   `robottt_seam_dims`, fed the metadata MEASURED off the real processor and the real collator
   (`tests/fixtures/groot_n17_seam_dims.json`, regenerated by
   `tests/fixtures/extract_groot_seam_dims.py` in the gr00t venv). For a test here to pass at a
   width the data does not have, the fixture would have to be wrong — and the extractor asserts the
   derivation against the collated tensors, so a wrong fixture cannot be written.

Pure-torch: no gr00t import, runs in the same venv as the rest of the port's tests.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
import pytest
import torch

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from vla_training.train.train_base._groot_robottt_common import (  # noqa: E402
    flatten_window_batch,
    robottt_seam_dims,
    sequence_conditioning,
)

FIXTURE = json.loads((Path(__file__).parent / "fixtures" / "groot_n17_seam_dims.json").read_text())


class _Meta:
    """A stand-in carrying only the attributes `robottt_seam_dims` reads off the real objects."""

    def __init__(self, **fields):
        self.__dict__.update(fields)


def _processor(**over):
    return _Meta(**{**FIXTURE["processor"], **over})


def _model_config(**over):
    fields = {k: v for k, v in FIXTURE["model_config"].items() if k != "input_embedding_dim"}
    return _Meta(**{**fields, **over})


#: THE DIMS EVERY FIXTURE BELOW IS BUILT FROM — the production derivation over measured metadata.
DIMS = robottt_seam_dims(_processor(), _model_config())
S = DIMS["state_dim"]  # 132 = state_history_length(1) * max_state_dim(132)
A = DIMS["action_dim"]  # 132 = max_action_dim
H = DIMS["action_horizon"]  # 40  = max_action_horizon (the PADDED chunk length)
HIST = DIMS["state_history_length"]  # 1
C = FIXTURE["cond_dim"]  # 1536 = the DiT inner width the readout rides
B, L = FIXTURE["collated"]["B"], FIXTURE["collated"]["L"]


def _batch():
    """A sequence batch whose every entry ENCODES its own (window, step) index, at MEASURED widths.

    state[b, t] is all-(b*L + t), so a transposition is visible in the values rather than only in a
    shape, which is the only way a test can see that class of bug.
    """
    tag = torch.arange(B * L, dtype=torch.float32).reshape(B, L)
    return {
        "state": (tag[:, :, None, None] + torch.zeros(B, L, HIST, S // HIST)),
        "action": (tag[:, :, None, None] + torch.zeros(B, L, H, A)),
        "action_mask": torch.ones(B, L, H, A, dtype=torch.bool),
        "embodiment_id": torch.full((B, L), 10, dtype=torch.long),
        "seq_window_len": torch.tensor(L),
        "seq_len": torch.full((B, L), L, dtype=torch.long),
        "loss_mask": torch.ones(B, L),
        "reset": torch.zeros(B, L, dtype=torch.bool),
    }


def _cfg(**over):
    """The production config builder, at the derived widths. Tests never hand-write a width."""
    import dataclasses

    from vla_training.train.train_base._groot_robottt_common import robottt_config_from_env

    cfg = robottt_config_from_env(
        cond_dim=C, state_dim=S, action_dim=A, action_horizon=H, dims_source=DIMS["dims_source"]
    )
    return dataclasses.replace(cfg, **over) if over else cfg


# --------------------------------------------------------------------------------------------
# The widths
# --------------------------------------------------------------------------------------------
def test_derived_dims_reproduce_the_measured_collated_tensors():
    """The whole point: the derivation and the real collator agree, so this file's dims are real."""
    seam, collated = FIXTURE["seam"], FIXTURE["collated"]
    assert [B, L, S] == seam["state_seq"], (DIMS, seam)
    assert [B, L, H, A] == seam["action_seq"], (DIMS, seam)
    # ...and the pre-flatten tensor really is [B, L, state_history_length, max_state_dim], i.e. the
    # head's `state.reshape(B, L, -1)` is a flatten of the history axis and not a lucky no-op.
    assert collated["state"] == [B, L, HIST, S // HIST]
    assert S == HIST * FIXTURE["processor"]["max_state_dim"]
    # The RoboCasa modality carries 16 real action steps x 12 real channels; the seam sees the
    # PADDED [40, 132] block. Reading H off the modality config instead of the processor is the
    # near-miss this pins.
    assert H != FIXTURE["raw_modality"]["action_timesteps"]
    assert A != FIXTURE["raw_modality"]["action_channels"]


def test_the_config_has_no_width_defaults_left_to_inherit():
    """The canary's root cause, pinned: a RoboTTTConfig without derived widths must not exist."""
    import dataclasses

    from workspace_models.networks.robottt_fast_weights import RoboTTTConfig

    with pytest.raises(ValueError, match=r"missing the data-determined width"):
        RoboTTTConfig(token_dim=16, fast_hidden=8, num_registers=4, cond_dim=C)
    for field in ("state_dim", "action_dim", "action_horizon"):
        with pytest.raises(ValueError, match=field):
            dataclasses.replace(_cfg(), **{field: -1})


def test_seam_dims_refuses_to_guess_when_the_metadata_is_absent():
    """No fallback path. `attach_robottt` used to answer 64 here, from a `hasattr` that was False."""
    with pytest.raises(AttributeError, match="max_state_dim"):
        robottt_seam_dims(_Meta(), _model_config())
    with pytest.raises(AttributeError, match="state_history_length"):
        robottt_seam_dims(_processor(), _Meta(max_state_dim=132, max_action_dim=132, action_horizon=40))


def test_seam_dims_rejects_a_processor_that_disagrees_with_the_model_config():
    """On the `start_from_checkpoint` path these come from two different files and CAN drift."""
    with pytest.raises(ValueError, match=r"max_state_dim=64 disagrees .*max_state_dim=132"):
        robottt_seam_dims(_processor(max_state_dim=64), _model_config())
    with pytest.raises(ValueError, match=r"max_action_horizon=16 disagrees .*action_horizon=40"):
        robottt_seam_dims(_processor(max_action_horizon=16), _model_config())


def test_a_width_mismatch_fails_loud_and_names_both_numbers_and_the_source():
    """The exact canary failure, reproduced — and now caught before `nn.Linear` mangles it.

    `mat1 and mat2 shapes cannot be multiplied (2x132 and 64x256)` names neither field nor side nor
    provenance. These messages name the tensor width, the cfg width, and where the cfg came from.
    """
    from workspace_models.networks.robottt_fast_weights import RoboTTTFastWeights

    stale = _cfg(
        token_dim=32,
        fast_hidden=16,
        num_registers=4,
        state_dim=64,
        action_dim=32,
        action_horizon=16,
        dims_source="RoboTTTConfig pi-lineage defaults",
    )
    mod = RoboTTTFastWeights(stale)
    with pytest.raises(ValueError, match=r"state width .*132.*cfg\.state_dim=64"):
        mod.condition(mod.init_state(B), torch.zeros(B, S))
    with pytest.raises(ValueError, match="pi-lineage defaults"):
        mod.condition(mod.init_state(B), torch.zeros(B, S))

    good_state = _cfg(token_dim=32, fast_hidden=16, num_registers=4, action_dim=32)
    mod = RoboTTTFastWeights(good_state)
    with pytest.raises(ValueError, match=r"action width .*132.*cfg\.action_dim=32"):
        mod.commit(mod.init_state(B), torch.zeros(B, S), torch.zeros(B, H, A))

    good_dim = _cfg(token_dim=32, fast_hidden=16, num_registers=4, action_horizon=16)
    mod = RoboTTTFastWeights(good_dim)
    with pytest.raises(ValueError, match=r"action horizon .*40.*cfg\.action_horizon=16"):
        mod.commit(mod.init_state(B), torch.zeros(B, S), torch.zeros(B, H, A))


# --------------------------------------------------------------------------------------------
# The pairing
# --------------------------------------------------------------------------------------------
def test_flatten_is_window_major_and_drops_sequence_only_keys():
    flat, batch, length = flatten_window_batch(_batch(), L)
    assert (batch, length) == (B, L)

    # Flat index b*L + t must be window b's step t — checked on the value tags, not the shapes.
    assert list(flat["state"].shape) == FIXTURE["flat"]["state"]
    assert list(flat["action"].shape) == FIXTURE["flat"]["action"]
    for b in range(B):
        for t in range(L):
            assert float(flat["state"][b * L + t, 0, 0]) == float(b * L + t)
            assert float(flat["action"][b * L + t, 0, 0]) == float(b * L + t)

    # Keys the head consumes itself must not reach the vendored forward.
    for key in ("seq_len", "seq_window_len", "loss_mask", "reset"):
        assert key not in flat
    # Non-windowed keys pass through untouched.
    assert tuple(flat["embodiment_id"].shape) == (B * L,)


def test_flatten_rejects_a_batch_with_no_window_axis():
    """A batch that lost its window axis means the sequence collator did not run."""
    bad = _batch()
    bad["state"] = torch.zeros(B, L + 1, HIST, S // HIST)
    with pytest.raises(ValueError, match="expected a window axis"):
        flatten_window_batch(bad, L)


class _TaggingFastWeights:
    """Stand-in whose output at step t of window b is the scalar (b*L + t), i.e. the flat index."""

    def run_sequence(self, state_seq, action_seq):
        batch, length = state_seq.shape[0], state_seq.shape[1]
        out = torch.zeros(length, batch, C)
        for b in range(batch):
            for t in range(length):
                out[t, b, :] = float(b * length + t)
        return out, {"w2": torch.zeros(batch, 3, 3)}


def test_conditioning_order_matches_the_flatten_order():
    """The invariant: cond[b*L + t] is window b step t — the same index the flatten produced."""
    flat, batch, length = flatten_window_batch(_batch(), L)
    cond, _ = sequence_conditioning(_TaggingFastWeights(), torch.zeros(B, L, S), torch.zeros(B, L, H, A))

    assert tuple(cond.shape) == (B * L, C)
    for b in range(B):
        for t in range(L):
            i = b * L + t
            assert float(cond[i, 0]) == float(i)
            # and it agrees with the observation that landed at the same flat index
            assert float(flat["state"][i, 0, 0]) == float(i)


def test_step_major_conditioning_is_distinguishable():
    """Non-vacuity: the transposed order must differ, or the test above proves nothing."""
    out_seq, _ = _TaggingFastWeights().run_sequence(torch.zeros(B, L, S), torch.zeros(B, L, H, A))
    window_major = out_seq.permute(1, 0, 2).reshape(B * L, C)
    step_major = out_seq.reshape(B * L, C)  # the tempting, WRONG line
    assert not torch.equal(window_major, step_major)


def test_real_module_roll_is_finite_and_apply_then_commit():
    """The real module through the same seam: finite output, and step 0 sees the ENTERING W_0.

    With the readout zero-initialised, O_0 must be exactly zero — that is the observable signature
    of apply-then-commit (D-1). If the wiring committed first, step 0 would be conditioned by W_1
    and, because the readout is zero at init, still be zero — so the test also perturbs the readout
    and checks O_0 is the value produced by W_0 rather than by W_1.
    """
    from workspace_models.networks.robottt_fast_weights import RoboTTTFastWeights

    torch.manual_seed(0)
    mod = RoboTTTFastWeights(_cfg(token_dim=32, fast_hidden=16, num_registers=4, window_len=L, tbptt_segment=L))
    with torch.no_grad():  # break the zero-init so O_t can be non-trivial
        mod.readout.weight.normal_(0, 0.1)
        mod.alpha.fill_(0.5)

    state_seq = torch.randn(B, L, S)
    action_seq = torch.randn(B, L, H, A)
    cond, w_final = sequence_conditioning(mod, state_seq, action_seq)
    assert tuple(cond.shape) == (B * L, C)
    assert torch.isfinite(cond).all()

    # O_0 must equal condition(W_0, s_0): the entering state, not the post-commit one.
    expected_0 = mod.condition(mod.init_state(B), state_seq[:, 0])
    torch.testing.assert_close(cond[0::L], expected_0, rtol=1e-5, atol=1e-6)
    committed = mod.commit(mod.init_state(B), state_seq[:, 0], action_seq[:, 0])
    assert not torch.allclose(mod.condition(committed, state_seq[:, 0]), expected_0), (
        "conditioning is identical before and after a commit — this fixture cannot tell "
        "apply-then-commit from commit-then-apply"
    )
    for leaf in w_final.values():
        assert torch.isfinite(leaf).all()


def test_tbptt_truncation_changes_gradients_but_not_forward_values():
    """G affects gradients only. Pinned at the MEASURED widths, where the roll is 40x wider than the
    toy fixture this used to run at — the forward equality is what lets G be a memory knob."""
    from workspace_models.networks.robottt_fast_weights import RoboTTTFastWeights

    torch.manual_seed(0)
    mod = RoboTTTFastWeights(_cfg(token_dim=32, fast_hidden=16, num_registers=4, window_len=L, tbptt_segment=L))
    with torch.no_grad():
        mod.readout.weight.normal_(0, 0.1)
        mod.alpha.fill_(0.5)
    state_seq, action_seq = torch.randn(B, L, S), torch.randn(B, L, H, A)

    full, _ = mod.run_sequence(state_seq, action_seq, tbptt_segment=L)
    cut, _ = mod.run_sequence(state_seq, action_seq, tbptt_segment=1)
    torch.testing.assert_close(full, cut, rtol=1e-6, atol=1e-7)

    grad_full = torch.autograd.grad(full.sum(), mod.w0_w1, retain_graph=True)[0]
    grad_cut = torch.autograd.grad(cut.sum(), mod.w0_w1)[0]
    assert not torch.allclose(grad_full, grad_cut), (
        "truncating BPTT to G=1 left the gradient to W_0 unchanged — the carry is not in the graph"
    )


def test_serve_reset_commit_cycle_is_finite_at_production_dims():
    """Serve-order regression at PRODUCTION geometry: reset -> (condition, commit) x 32, all finite.

    Same reason `test_stability_at_production_dims` exists on the module: the toy dims that unit
    tests default to are stable under an inner step that diverges at d=256/h=128. "Production dims"
    now means the MEASURED ones — d=256, h=128, C=1536, state 132, action 40x132 — rather than a
    number typed into this file, which is the second half of the same lesson.
    """
    from workspace_models.networks.robottt_fast_weights import RoboTTTFastWeights

    torch.manual_seed(0)
    mod = RoboTTTFastWeights(_cfg()).eval()
    assert (mod.cfg.token_dim, mod.cfg.fast_hidden) == (256, 128), mod.cfg
    assert mod.state_in.in_features == S and mod.action_in.in_features == A

    w = mod.init_state(2)
    for step in range(32):
        state = torch.randn(2, S)
        cond = mod.condition(w, state)
        assert torch.isfinite(cond).all(), f"conditioning went non-finite at serve step {step}"
        w = mod.commit(w, state, torch.randn(2, H, A))
        for name, leaf in w.items():
            assert torch.isfinite(leaf).all(), f"fast weight {name} diverged at serve step {step}"
    assert float(w["w2"].abs().max()) < 1e3, "fast weights growing without bound"


def test_env_config_reads_the_documented_knobs(monkeypatch):
    from vla_training.train.train_base._groot_robottt_common import robottt_config_from_env

    for key, value in {
        "WSM_TTT_TOKEN_DIM": "128",
        "WSM_TTT_FAST_HIDDEN": "64",
        "WSM_TTT_NUM_REGISTERS": "8",
        "WSM_TTT_INNER_LR": "0.05",
        "WSM_TTT_GATE_INIT": "1e-4",
        "WSM_SEQ_WINDOW_LEN": "6",
    }.items():
        monkeypatch.setenv(key, value)
    cfg = robottt_config_from_env(
        cond_dim=C,
        dims_source=DIMS["dims_source"],
        **{k: DIMS[k] for k in ("state_dim", "action_dim", "action_horizon")},
    )
    assert (cfg.token_dim, cfg.fast_hidden, cfg.num_registers) == (128, 64, 8)
    assert cfg.base_inner_lr == 0.05 and cfg.gate_init == 1e-4
    # G defaults to L, i.e. full BPTT over the window unless explicitly truncated.
    assert cfg.window_len == 6 and cfg.tbptt_segment == 6
    assert cfg.cond_dim == C
    # The widths pass through UNTOUCHED and carry their provenance: no env knob is consulted for
    # them unless one is set, and the ttt yamls set none.
    assert (cfg.state_dim, cfg.action_dim, cfg.action_horizon) == (S, A, H)
    assert "robottt_seam_dims" in cfg.dims_source and "OVERRIDE" not in cfg.dims_source


def test_a_width_override_is_recorded_in_the_provenance(monkeypatch):
    """The escape hatch exists, but it may not hide: the override lands in `dims_source`, so the
    shape error it eventually causes blames the override and not the derivation."""
    from vla_training.train.train_base._groot_robottt_common import robottt_config_from_env

    monkeypatch.setenv("WSM_TTT_STATE_DIM", "64")
    cfg = robottt_config_from_env(
        cond_dim=C,
        dims_source=DIMS["dims_source"],
        **{k: DIMS[k] for k in ("state_dim", "action_dim", "action_horizon")},
    )
    assert cfg.state_dim == 64
    assert "OVERRIDES" in cfg.dims_source and "'state_dim': (132, 64)" in cfg.dims_source


def test_numpy_is_not_required_by_the_seam():
    """The flatten/conditioning seam is pure torch — guards against a stray np dependency."""
    assert np is not None  # imported above only to assert the seam does not need it
    flat, _, _ = flatten_window_batch(_batch(), L)
    assert all(isinstance(v, torch.Tensor) for v in flat.values())
