"""Dependency-free identity table shared by launch, train, and evaluation infrastructure."""

from typing import Literal

Arm = Literal[
    "s0",
    "q0",
    "q0_noforce",
    "q1",
    "a6",
    "q2",
    "q2_noforce",
    "q3",
    "q0v",
    "q2v",
    "wsm_cfg",
    "wsm_tanh",
    "wsm_d8",
    "wsm_d8_drop05",
    "wsm_d16",
    "wsm_d16_drop05",
    "gdn8_jepa_l01_k1",
    "ptrm",
    "jepa_l01_k1",
    "jepa_l1_k32",
    "jepa_l01_k16",
    "salient",
    "causal_v1",
    "official_recipe_lerobot",
    "v4_s0",
    "v4_q0",
    "v4_q2",
    "v4_wsm_tanh",
    "v4_wsm_cfg",
    "v4_wsm_gdn8_drop00",
    "v4_wsm_gdn8_drop02",
    "v4_wsm_gdn16_drop00",
    "v4_wsm_gdn16_drop02",
    "v4_jepa_visreg_l01_k1",
    "v4_gdn8_jepa_visreg_l01_k1",
    "v4_cfg_jepa_visreg_l01_k1",
    "v4_ptrm",
]
ARM_IDS = (
    "s0",
    "q0",
    "q0_noforce",
    "q1",
    "a6",
    "q2",
    "q2_noforce",
    "q3",
    "q0v",
    "q2v",
    "wsm_cfg",
    "wsm_tanh",
    "wsm_d8",
    "wsm_d8_drop05",
    "wsm_d16",
    "wsm_d16_drop05",
    "gdn8_jepa_l01_k1",
    "ptrm",
    "jepa_l01_k1",
    "jepa_l1_k32",
    "jepa_l01_k16",
    "salient",
    "causal_v1",
    "official_recipe_lerobot",
    "v4_s0",
    "v4_q0",
    "v4_q2",
    "v4_wsm_tanh",
    "v4_wsm_cfg",
    "v4_wsm_gdn8_drop00",
    "v4_wsm_gdn8_drop02",
    "v4_wsm_gdn16_drop00",
    "v4_wsm_gdn16_drop02",
    "v4_jepa_visreg_l01_k1",
    "v4_gdn8_jepa_visreg_l01_k1",
    "v4_cfg_jepa_visreg_l01_k1",
    "v4_ptrm",
)
NOFORCE_ARM_IDS = ("q0_noforce", "q2_noforce")
TRAINING_ARM_IDS = ARM_IDS
OFFICIAL_RECIPE_LEROBOT_ARM = "official_recipe_lerobot"
OFFICIAL_RECIPE_LEROBOT_LABEL = "recipe_matched_lerobot_not_exact_source_or_data_reproduction"
OFFICIAL_RECIPE_LEROBOT_STEPS = 80_000
OFFICIAL_RECIPE_LEROBOT_MILESTONES = (60_000, 70_000, 79_999)
SEQUENCE_ARMS = frozenset(
    {
        "q0",
        "q1",
        "a6",
        "q2",
        "q3",
        "q0v",
        "q2v",
        "v4_q0",
        "v4_q2",
        *NOFORCE_ARM_IDS,
    }
)
ROBOTT_ARMS = frozenset({"q2", "q3", "q2v", "q2_noforce", "v4_q2"})
V4_ARM_IDS = frozenset(
    {
        "v4_s0",
        "v4_q0",
        "v4_q2",
        "v4_wsm_tanh",
        "v4_wsm_cfg",
        "v4_wsm_gdn8_drop00",
        "v4_wsm_gdn8_drop02",
        "v4_wsm_gdn16_drop00",
        "v4_wsm_gdn16_drop02",
        "v4_jepa_visreg_l01_k1",
        "v4_gdn8_jepa_visreg_l01_k1",
        "v4_cfg_jepa_visreg_l01_k1",
        "v4_ptrm",
    }
)
V4_NEW_PARAMETER_SUBTREES = {
    "v4_s0": (),
    "v4_q0": (),
    "v4_q2": ("robottt_fast",),
    "v4_wsm_tanh": ("wsm_tanh_cond",),
    "v4_wsm_cfg": ("wsm_cfg2_cond",),
    "v4_wsm_gdn8_drop00": ("wsm_tanh_cond",),
    "v4_wsm_gdn8_drop02": ("wsm_tanh_cond",),
    "v4_wsm_gdn16_drop00": ("wsm_tanh_cond",),
    "v4_wsm_gdn16_drop02": ("wsm_tanh_cond",),
    "v4_jepa_visreg_l01_k1": ("wsm_jepa_head",),
    "v4_gdn8_jepa_visreg_l01_k1": ("wsm_tanh_cond", "wsm_jepa_head"),
    "v4_cfg_jepa_visreg_l01_k1": ("wsm_cfg2_cond", "wsm_jepa_head"),
    "v4_ptrm": ("wsm_tanh_cond",),
}
WORKSPACE_ARMS = frozenset(
    {
        "q3",
        "q1",
        "wsm_cfg",
        "wsm_tanh",
        "wsm_d8",
        "wsm_d8_drop05",
        "wsm_d16",
        "wsm_d16_drop05",
        "gdn8_jepa_l01_k1",
        "ptrm",
        "jepa_l01_k1",
        "jepa_l1_k32",
        "jepa_l01_k16",
        "salient",
        "causal_v1",
        "v4_wsm_tanh",
        "v4_wsm_cfg",
        "v4_wsm_gdn8_drop00",
        "v4_wsm_gdn8_drop02",
        "v4_wsm_gdn16_drop00",
        "v4_wsm_gdn16_drop02",
        "v4_jepa_visreg_l01_k1",
        "v4_gdn8_jepa_visreg_l01_k1",
        "v4_cfg_jepa_visreg_l01_k1",
        "v4_ptrm",
    }
)
