#!/usr/bin/env python3
"""Replay RoboCerebra raw demos in LIBERO and emit per-episode LeRobot payloads.

Why a replay at all: the published RoboCerebra ``demo.hdf5`` files carry **only**
``data/demo_1/{actions,states}`` plus the scene ``model_file``. There are no images and no
proprioception -- every observation has to be regenerated by pinning the MuJoCo sim state and
rendering, exactly like ``rlds_dataset_builder/regenerate_robocerebra_dataset.py`` upstream.
That is also why the authors' RLDS exports are 131 GB against 2.5 GB of raw hdf5.

What this writes, per case, under ``<out>/<scene>/<case>/_episode/``:

* ``image.mp4`` / ``wrist_image.mp4`` -- h264/yuv420p/crf23, 256px, agentview and
  ``robot0_eye_in_hand``, both rotated 180 degrees (``[::-1, ::-1]``) so they match BOTH
  openpi's ``examples/libero/main.py`` inference preprocessing AND the authors' RLDS builder.
* ``arrays.npz`` -- ``state`` [T,8] float32, ``actions`` [T,7] float32, ``subtask_index`` [T],
  ``source_frame_index`` [T] (index into the raw demo, so no-op filtering is reversible).
* ``episode.json`` -- instruction strings, subtask boundaries, action-clipping counters,
  scene/bddl/distractor provenance.

State layout is ``concat(eef_pos[3], quat2axisangle(eef_quat)[3], gripper_qpos[2])`` -- the
identical construction openpi uses for ``observation/state`` on LIBERO, so the pi05_libero
checkpoint's 8-d state semantics carry over unchanged.

Two conventions are applied by default because both are required for parity with the
pi05_libero init:

* ``--drop-noops`` (default on) mirrors the authors' ``is_noop`` filter, which is also what
  produced the ``*_no_noops`` RLDS that pi0/pi0.5 LIBERO was trained on.
* ``--clip-actions`` (default on) clips to [-1, 1]. RoboCerebra's recorded actions run to
  +-5.625 / +-11.25 on the translation axes for 2-9% of steps, but robosuite's
  ``Controller.scale_action`` clips to ``[input_min, input_max] = [-1, 1]`` before scaling, so
  those magnitudes were *never executed*. Storing them unclipped would poison the action
  quantiles relative to the released LIBERO norm stats.

Run this under the LIBERO sim venv (robosuite 1.4.0 / mujoco 2.3.2), which cannot coexist with
the robocasa robosuite 1.5.2 fork:

    LIBERO_CONFIG_PATH=$WSM/robocerebra/libero_config \
    PYTHONPATH=$WSM/robocerebra/code/LIBERO MUJOCO_GL=egl \
    $WSM/robocerebra/venv_sim/bin/python replay_shard.py --cases ... --out ...
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import time
from pathlib import Path

import numpy as np

FPS = 20
IMAGE_SIZE = 256
CAMERAS = {"image": "agentview_image", "wrist_image": "robot0_eye_in_hand_image"}
# BDDL problem name -> the scene bucket the raw trainset uses.
SCENE_OF_PROBLEM = {
    "libero_coffee_table_manipulation": "coffee_table",
    "libero_kitchen_tabletop_manipulation": "kitchen_table",
    "libero_study_tabletop_manipulation": "study_table",
    "libero_living_room_tabletop_manipulation": "living_room_table",
}
STEP_RE = re.compile(r"Step:\s*(.*?)\s*\n\s*\[\s*(\d+)\s*,\s*(\d+)\s*\]")


def log(message: str) -> None:
    print(f"[{time.strftime('%H:%M:%S')}] {message}", flush=True)


def is_noop(action: np.ndarray, prev_action: np.ndarray | None, threshold: float = 1e-4) -> bool:
    """Verbatim from ``regenerate_robocerebra_dataset.py`` so our frame set matches theirs."""
    if prev_action is None:
        return bool(np.linalg.norm(action[:-1]) < threshold)
    return bool(np.linalg.norm(action[:-1]) < threshold and action[-1] == prev_action[-1])


def parse_task_description(path: Path) -> tuple[str, list[tuple[str, int, int]]]:
    """Return ``(task_line, [(step_text, start_frame, end_frame), ...], dropped_count)``.

    The raw ``task_description.txt`` is the only place the subtask segmentation lives, and the
    ``[start, end]`` frame pairs index the *unfiltered* demo, so they must be translated after
    no-op filtering.
    """
    text = path.read_text(encoding="utf-8")
    task_line = ""
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("Task:"):
            task_line = stripped.split(":", 1)[1].strip()
            break
    steps = [(m.group(1).strip(), int(m.group(2)), int(m.group(3))) for m in STEP_RE.finditer(text)]
    if not steps:
        raise ValueError(f"no [start, end] annotated steps parsed from {path}")
    # A handful of cases carry a transposed interval (e.g. `[3315, 2511]` in coffee_table/case49),
    # which makes the end frames non-monotone. Upstream's parser hard-raises on this, so those
    # cases are missing from the authors' own RLDS. Sort by end frame (as upstream does) and drop
    # whatever still cannot be ordered, rather than losing the whole trajectory. The count of
    # dropped subtasks is recorded per episode so it stays auditable.
    steps.sort(key=lambda entry: entry[2])
    monotone, dropped = [], 0
    for entry in steps:
        if monotone and entry[2] <= monotone[-1][2]:
            dropped += 1
            continue
        monotone.append(entry)
    return task_line, monotone, dropped


def open_video_writer(path: Path, size: int) -> subprocess.Popen:
    """h264/yuv420p/crf23 -- same encoder settings the remembench LeRobot render pins."""
    path.parent.mkdir(parents=True, exist_ok=True)
    command = [
        "ffmpeg",
        "-hide_banner",
        "-loglevel",
        "error",
        "-y",
        "-f",
        "rawvideo",
        "-pix_fmt",
        "rgb24",
        "-s",
        f"{size}x{size}",
        "-r",
        str(FPS),
        "-i",
        "pipe:0",
        "-c:v",
        "libx264",
        "-pix_fmt",
        "yuv420p",
        "-crf",
        "23",
        "-an",
        str(path),
    ]
    return subprocess.Popen(command, stdin=subprocess.PIPE)


def make_env(bddl_path: Path, size: int):
    import libero.libero.envs.bddl_utils as BDDLUtils
    from libero.libero.envs import TASK_MAPPING
    from robosuite import load_controller_config

    problem_info = BDDLUtils.get_problem_info(str(bddl_path))
    env = TASK_MAPPING[problem_info["problem_name"]](
        bddl_file_name=str(bddl_path),
        robots=["Panda"],
        controller_configs=load_controller_config(default_controller="OSC_POSE"),
        has_renderer=False,
        has_offscreen_renderer=True,
        camera_names=["agentview", "robot0_eye_in_hand"],
        ignore_done=True,
        use_camera_obs=True,
        reward_shaping=True,
        camera_heights=size,
        camera_widths=size,
        control_freq=FPS,
    )
    # The two grip-site markers render as green blobs in agentview; the authors hide them.
    model = env.sim.model
    for site in ("gripper0_grip_site_cylinder", "gripper0_grip_site"):
        if site in model.site_names:
            model.site_rgba[model.site_name2id(site)][3] = 0.0
    return env, problem_info


def subtask_index_per_frame(kept: np.ndarray, steps: list[tuple[str, int, int]]) -> np.ndarray:
    """Map every kept frame onto the subtask whose ``[start, end)`` window contains it.

    Frames before the first window (rare -- some annotations start at a nonzero frame) are
    assigned to subtask 0; frames past the final ``end`` are assigned to the last subtask.
    """
    ends = np.array([end for _, _, end in steps])
    idx = np.searchsorted(ends, kept, side="right")
    return np.clip(idx, 0, len(steps) - 1).astype(np.int32)


def replay_case(
    case_dir: Path, out_dir: Path, *, size: int, drop_noops: bool, clip_actions: bool, limit: int | None
) -> dict:
    import h5py
    import robosuite.utils.transform_utils as T

    bddl_files = sorted(case_dir.glob("*.bddl"))
    if not bddl_files:
        raise FileNotFoundError(f"no .bddl in {case_dir}")
    bddl_path = bddl_files[0]
    task_line, steps, dropped_subtasks = parse_task_description(case_dir / "task_description.txt")

    with h5py.File(case_dir / "demo.hdf5", "r") as handle:
        demo = handle["data"]["demo_1"]
        raw_states = demo["states"][()]
        raw_actions = demo["actions"][()]
    if limit is not None:
        raw_states, raw_actions = raw_states[:limit], raw_actions[:limit]

    env, problem_info = make_env(bddl_path, size)
    env.reset()

    payload_dir = out_dir / "_episode"
    payload_dir.mkdir(parents=True, exist_ok=True)
    writers = {name: open_video_writer(payload_dir / f"{name}.mp4", size) for name in CAMERAS}

    kept, states, actions = [], [], []
    prev_action = None
    started = time.time()
    for frame, (sim_state, action) in enumerate(zip(raw_states, raw_actions)):
        if drop_noops and is_noop(action, prev_action):
            prev_action = action
            continue
        prev_action = action

        env.sim.set_state_from_flattened(sim_state)
        env.sim.forward()
        env._post_process()
        env._update_observables(force=True)
        obs = env._get_observations()

        kept.append(frame)
        states.append(
            np.concatenate(
                (obs["robot0_eef_pos"], T.quat2axisangle(obs["robot0_eef_quat"]), obs["robot0_gripper_qpos"])
            )
        )
        actions.append(action)
        for name, obs_key in CAMERAS.items():
            # 180-degree rotation: matches openpi's LIBERO client and the authors' RLDS export.
            frame_rgb = np.ascontiguousarray(obs[obs_key][::-1, ::-1])
            writers[name].stdin.write(frame_rgb.tobytes())

    for writer in writers.values():
        writer.stdin.close()
    for writer in writers.values():
        if writer.wait() != 0:
            raise RuntimeError("ffmpeg failed while encoding an episode video")
    env.close()

    kept_arr = np.asarray(kept, dtype=np.int64)
    state_arr = np.asarray(states, dtype=np.float32)
    action_arr = np.asarray(actions, dtype=np.float32)
    out_of_range = int((np.abs(action_arr) > 1.0).sum())
    if clip_actions:
        action_arr = np.clip(action_arr, -1.0, 1.0)
    sub_idx = subtask_index_per_frame(kept_arr, steps)

    np.savez_compressed(
        payload_dir / "arrays.npz",
        state=state_arr,
        actions=action_arr,
        subtask_index=sub_idx,
        source_frame_index=kept_arr,
    )

    elapsed = time.time() - started
    meta = {
        "scene": SCENE_OF_PROBLEM.get(problem_info["problem_name"], problem_info["problem_name"]),
        "case": case_dir.name,
        "problem_name": problem_info["problem_name"],
        "bddl_file": bddl_path.name,
        "language_instruction": problem_info.get("language_instruction", ""),
        "task_line": task_line,
        "distractor": (case_dir / "distractor_name.txt").read_text().strip()
        if (case_dir / "distractor_name.txt").is_file()
        else "",
        "subtasks": [
            {"index": i, "text": text, "raw_start": start, "raw_end": end, "frames": int((sub_idx == i).sum())}
            for i, (text, start, end) in enumerate(steps)
        ],
        "dropped_subtasks": dropped_subtasks,
        "num_frames": int(len(kept_arr)),
        "num_raw_frames": int(len(raw_states)),
        "dropped_noop_frames": int(len(raw_states) - len(kept_arr)),
        "actions_out_of_unit_range": out_of_range,
        "actions_clipped": bool(clip_actions),
        "image_size": size,
        "fps": FPS,
        "replay_seconds": round(elapsed, 2),
    }
    (payload_dir / "episode.json").write_text(json.dumps(meta, indent=2))
    log(
        f"{meta['scene']}/{meta['case']}: {meta['num_frames']}/{meta['num_raw_frames']} frames, "
        f"{len(steps)} subtasks, {elapsed:.1f}s ({len(kept_arr) / max(elapsed, 1e-6):.0f} fps)"
    )
    return meta


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--cases", nargs="+", required=True, help="raw case directories (each holding demo.hdf5 + *.bddl)"
    )
    parser.add_argument("--out", required=True, help="payload root; one subdir per case")
    parser.add_argument("--image-size", type=int, default=IMAGE_SIZE)
    parser.add_argument("--drop-noops", dest="drop_noops", action="store_true", default=True)
    parser.add_argument("--keep-noops", dest="drop_noops", action="store_false")
    parser.add_argument("--clip-actions", dest="clip_actions", action="store_true", default=True)
    parser.add_argument("--no-clip-actions", dest="clip_actions", action="store_false")
    parser.add_argument(
        "--limit-frames", type=int, default=None, help="debug: truncate each demo to this many raw frames"
    )
    parser.add_argument("--skip-existing", action="store_true")
    args = parser.parse_args()

    out_root = Path(args.out)
    failures = []
    for raw in args.cases:
        case_dir = Path(raw)
        scene_hint = case_dir.parent.name
        dest = out_root / scene_hint / case_dir.name
        if args.skip_existing and (dest / "_episode" / "episode.json").is_file():
            log(f"skip existing {scene_hint}/{case_dir.name}")
            continue
        try:
            replay_case(
                case_dir,
                dest,
                size=args.image_size,
                drop_noops=args.drop_noops,
                clip_actions=args.clip_actions,
                limit=args.limit_frames,
            )
        except Exception as exc:  # noqa: BLE001 - one bad case must not kill the shard
            log(f"FAILED {case_dir}: {type(exc).__name__}: {exc}")
            failures.append({"case": str(case_dir), "error": f"{type(exc).__name__}: {exc}"})

    if failures:
        # PID-suffixed: shards run in parallel under xargs and would otherwise clobber each
        # other's failure list. The authoritative check is still "which cases lack an
        # episode.json", which `--skip-existing` makes trivially re-runnable.
        report = out_root / f"_failures.{os.getpid()}.json"
        report.write_text(json.dumps(failures, indent=2))
        log(f"{len(failures)} case(s) failed; see {report}")
        sys.exit(1)


if __name__ == "__main__":
    main()
